import {Component, OnInit} from '@angular/core';
import {Organization} from '../organization';
import {StandaloneWrapperController, StandaloneWrapperDataSchema} from '../standalone-wrapper/standaloneWrapperController';

const standaloneWrapperSchema: StandaloneWrapperDataSchema = {
  inputs: {
    organizations: [{
      id: String,
      originId: String,
      name: String,
    }]
  },
  outputs: ['orgSelected']
};

const schema: StandaloneWrapperController = new StandaloneWrapperController(standaloneWrapperSchema);

@Component({
  selector: 'app-standalone-buyer-org-select',
  templateUrl: './buyer-org-select.standalone.component.html',
  styleUrls: ['./buyer-org-select.component.scss']
})

export class StandaloneBuyerOrgSelectComponent implements OnInit {

  organizations: Organization[] = [];

  controller: StandaloneWrapperController = schema;

  constructor() { }

  ngOnInit() {
  }

  onMountComponentClicked(payload) {
    this.organizations = payload.autoGeneratedData.organizations;
  }

  onOrgSelected(): void {
  }
}
